# ==========================================
# 1. 任务指挥官配置
# ==========================================
mission:
  takeoff_height: 1.2
  wp_recognition: [4.0, 0.0]
  wp_airdrop: [4.0, -3.5]
  wp_strike: [0.0, -3.5]

# ==========================================
# 2. 测绘部 (GridMap) 配置
# ==========================================
planner:
  map_resolution: 0.1
  map_width_m: 20.0
  map_height_m: 20.0
  map_origin_x: -5.0
  map_origin_y: -10.0
  map_front_x: 5.3
  map_back_x: -1.0
  map_left_y: 1.0
  map_right_y: -7.5
  map_exp: 0.2
  map_intensity_threshold: 0.1
  safe_distance: 0.00

# ==========================================
# 3. 调度部 (Manager) 配置
# ==========================================
manager:
  max_vel: 1.0
  max_acc: 1.5
  ctrl_pt_dist: 0.3    # B样条控制点间距

# ==========================================
# 4. 优化部 (L-BFGS Optimizer) 配置
# ==========================================
bspline_optimizer:
  weight_smooth: 2.0       # 越高轨迹越直
  weight_collision: 6.0    # 越高越怕撞墙
  weight_feasibility: 0.1  # [修复] 动力学权重降低 10 倍，防止梯度爆炸
  safe_distance: 0.3       # 避障安全/膨胀距离 (非常关键)
  max_vel: 1.0
  max_acc: 1.5
  max_iteration_num: 300   # 优化迭代次数